#!/bin/bash

AWS_REGION=us-west-2



# cat << EOF > ecs-secret-permission.json 
# {
#   "Version": "2012-10-17",
#   "Statement": [
#     {
#       "Effect": "Allow",
#       "Action": [
#         "kms:Decrypt",
#         "secretsmanager:GetSecretValue"
#       ],
#       "Resource": [
#         "arn:aws:secretsmanager:us-west-2:882103041271:secret:ghcr-repository-secret-kZD4W2",
#         "arn:aws:kms:us-west-2:882103041271:key/3b434814-3ca5-4ab9-af51-bb5d5eab5e2d"     
#       ]
#     }
#   ]
# }
# EOF

# aws iam create-role \
# --role-name ecsDevenTaskExecutionRole \
# --assume-role-policy-document file://ecs-trust-policy.json

# aws iam attach-role-policy \
# --role-name ecsDevenTaskExecutionRole \
# --policy-arn arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

# aws iam put-role-policy \
# --role-name ecsDevenTaskExecutionRole \
# --policy-name ECS-SecretsManager-Permission \
# --policy-document file://ecs-secret-permission.json


ecs-cli up \
--cluster deven-cluster \
--region us-west-2 \
--launch-type FARGATE 

aws ec2 describe-security-groups \
--filters Name=vpc-id,Values=vpc-0addbdd01a730e87d \
--region us-west-2

aws ec2 authorize-security-group-ingress \
--group-id sg-0edd9dffe9b7dc627 \
--protocol tcp \
--port 22 \
--cidr 0.0.0.0/0 \
--region us-west-2

cat << EOF > docker-compose.yml
version: "3"
services:
    web:
        image: ghcr.io/rennochj/deven-amazon-base:latest
        ports:
            - 22:22
EOF

cat << EOF > ecs-params.yml
version: 1
task_definition:
  task_execution_role: ecsDevenTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
  services:
    web:
        repository_credentials: 
            credentials_parameter: "arn:aws:secretsmanager:us-west-2:882103041271:secret:ghcr-repository-secret-kZD4W2"
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-0ddc83af8fbe650c4"
        - "subnet-0131c283022f040ac"
      security_groups:
        - "sg-0edd9dffe9b7dc627"
      assign_public_ip: ENABLED
EOF

# ecs-cli compose \
# --project-name deven-service \
# --cluster deven-cluster \
# --region us-west-2 \
# service up \
# --launch-type FARGATE
