#! /bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

terraform -chdir="$SCRIPT_DIR/.deven/server" destroy -var "current-user=$USER" -auto-approve -target "module.deven-docker-instance.docker_container.deven" $@
