#! /bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

terraform -chdir="$SCRIPT_DIR/.deven-ebs-volume" apply \
    -var "current-user=$USER" \
    -auto-approve $@ 
