#! /bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

terraform -chdir="$SCRIPT_DIR/.deven-ec2" destroy \
    -var "deven-workspace-volume-id=$DEVEN_WORKSPACE_VOLUME_ID" \
    -auto-approve $@
