#! /bin/bash

set -e -v

WORKSPACE_VOLUME_NAME="rennochj-playgroud-workspace"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DEVEN_WORKSPACE_VOLUME_ID=$(aws ec2 describe-volumes --filters "Name=tag:Name,Values=$WORKSPACE_VOLUME_NAME" --output=json --region us-west-2 | jq -r '.Volumes[0].VolumeId')

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SSH_HOME=~/.ssh
DEVEN_NAME=deven
DEVEN_NAMESPACE=deven

USER_DATA=$(cat <<EOF
yum update -y
amazon-linux-extras install docker -y
service docker start
usermod -a -G docker ec2-user
EOF
)

echo "User Data: $USER_DATA"
echo "Using DEVEN_WORKSPACE_VOLUME_ID = $DEVEN_WORKSPACE_VOLUME_ID"

if [ ! -f $SSH_HOME/$DEVEN_NAME-id_rsa ]; then
    ssh-keygen -t rsa -b 4096 -f $SSH_HOME/$DEVEN_NAME-id_rsa -q -N ""
fi

terraform -chdir="$SCRIPT_DIR/.deven-ec2" apply \
    -var "deven-workspace-volume-id=$DEVEN_WORKSPACE_VOLUME_ID" \
    -var "public-key-file=$SSH_HOME/$DEVEN_NAME-id_rsa.pub" \
    -var "deven-instance-user-data=$USER_DATA" \
    -auto-approve $@ 

SSH_PORT=22
DEVEN_USER="ec2-user"
HOST=$(terraform -chdir="$SCRIPT_DIR/.deven-ec2" output -raw "host")

if [ ! -d $SSH_HOME/config.d ]; then

    echo "Creating ~/.ssh/config.d"
    mkdir -p $SSH_HOME/config.d

    if [ -f $SSH_HOME/config ]; then
        echo "Moving ~/.ssh/config"
        mv $SSH_HOME/config $SSH_HOME/config.d/
    fi

fi

touch $SSH_HOME/config.d/$DEVEN_NAME.config
printf "HOST $DEVEN_NAME\n    HostName $HOST\n    User $DEVEN_USER\n    Port $SSH_PORT\n    IdentityFile $SSH_HOME/$DEVEN_NAME-id_rsa\n    StrictHostKeyChecking no\n    UserKnownHostsFile /dev/null\n\n" > ~/.ssh/config.d/$DEVEN_NAME.config

touch $SSH_HOME/config
printf "# This file is machine generated from the concatenation of all configuration files from config.d\n" > $SSH_HOME/config
printf "# cat config.d/* > ./config\n\n" >> $SSH_HOME/config
cat $SSH_HOME/config.d/* >> $SSH_HOME/config
