#! /bin/bash

set -e

WORKSPACE_VOLUME_NAME="rennochj-playgroud-workspace"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SSH_HOME=~/.ssh
DEVEN_NAME=deven
DEVEN_NAMESPACE=deven
DEVEN_WORKSPACE_VOLUME_ID=$(aws ec2 describe-volumes --filters "Name=tag:Name,Values=$WORKSPACE_VOLUME_NAME" --output=json --region us-west-2 | jq -r '.Volumes[0].VolumeId')
KUBECONFIG=~/.kube/deven-eks.config

echo "Using KUBECONFIG = $KUBECONFIG"
echo "Using DEVEN_WORKSPACE_VOLUME_ID = $DEVEN_WORKSPACE_VOLUME_ID"

if [ ! -f $SSH_HOME/$DEVEN_NAME-id_rsa ]; then
    ssh-keygen -t rsa -b 4096 -f $SSH_HOME/$DEVEN_NAME-id_rsa -q -N ""
fi

terraform -chdir="$SCRIPT_DIR/.deven-eks" apply \
    -var "registry-username=rennochj" \
    -var "registry-password=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" \
    -var "current-user=$USER" \
    -var "public-key-file=$SSH_HOME/$DEVEN_NAME-id_rsa.pub" \
    -var "kubernetes-config=$KUBECONFIG" \
    -var "deven-instance-name=$DEVEN_NAME" \
    -var "deven-namespace=$DEVEN_NAMESPACE" \
    -var "deven-workspace-volume-id=$DEVEN_WORKSPACE_VOLUME_ID" \
    -var "workspace-git-repo=https://github.com/rennochj/deven.git"  \
    -var "deven-image=ghcr.io/rennochj/deven-amazon-base:latest"  \
    -auto-approve $@ 

SSH_PORT=$(terraform -chdir="$SCRIPT_DIR/.deven-k8s" output -raw "ssh-port")
DEVEN_NAME=$(terraform -chdir="$SCRIPT_DIR/.deven-k8s" output -raw "deven-instance-name")
# HOST=$(terraform -chdir="$SCRIPT_DIR/.deven-k8s" output -raw "host")
HOST="localhost"

if [ ! -d $SSH_HOME/config.d ]; then

    echo "Creating ~/.ssh/config.d"
    mkdir -p $SSH_HOME/config.d

    if [ -f $SSH_HOME/config ]; then
        echo "Moving ~/.ssh/config"
        mv $SSH_HOME/config $SSH_HOME/config.d/
    fi

fi

touch $SSH_HOME/config.d/$DEVEN_NAME.config
printf "HOST $DEVEN_NAME\n    HostName $HOST\n    User deven\n    Port $SSH_PORT\n    IdentityFile $SSH_HOME/$DEVEN_NAME-id_rsa\n    StrictHostKeyChecking no\n    UserKnownHostsFile /dev/null\n\n" > ~/.ssh/config.d/$DEVEN_NAME.config

touch $SSH_HOME/config
printf "# This file is machine generated from the concatenation of all configuration files from config.d\n" > $SSH_HOME/config
printf "# cat config.d/* > ./config\n\n" >> $SSH_HOME/config
cat $SSH_HOME/config.d/* >> $SSH_HOME/config

KUBECONFIG=$KUBECONFIG kubectl port-forward $DEVEN_NAME $SSH_PORT:22 --namespace $DEVEN_NAME > /dev/null 2>&1 &
