#! /bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

KUBECONFIG=~/.kube/deven-eks.config

terraform -chdir="$SCRIPT_DIR/.deven-eks" destroy \
    -var "current-user=$USER" \
    -var "kubernetes-config=$KUBECONFIG" \
    -var "registry-username=" \
    -var "registry-password=" \
    -var "deven-workspace-volume-id=" \
    -auto-approve $@
