#!/bin/bash

set -x

export DEVEN_SSH_HOME=~/.ssh
export DEVEN_SSH_PORT=22
export DEVEN_SSH_USER=ec2-user
export DEVEN_INSTANCE_NAME="deven"

export TF_VAR_current_user="$USER"
export TF_VAR_public_key_file="$DEVEN_PUBLIC_KEY_FILE" 
export TF_VAR_deven_instance_name="$DEVEN_INSTANCE_NAME" 
export TF_VAR_workspace_git_repo="https://github.com/rennochj/deven.git"
export TF_VAR_deven_image="ghcr.io/rennochj/deven-amazon-base:latest" 
export TF_VAR_public_key_file="$DEVEN_SSH_HOME/$DEVEN_INSTANCE_NAME-id_rsa.pub"
export TF_VAR_ssh_port=$DEVEN_SSH_PORT
export TF_VAR_aws_availability_zone="us-west-2a"
export TF_VAR_deven_workspace="$USER-deven-workspace"
export TF_VAR_deven_workspace_volume_id=$(aws ec2 describe-volumes --filters "Name=tag:Name,Values=$TF_VAR_deven_workspace" --output=json --region us-west-2 | jq -r '.Volumes[0].VolumeId')
