#! /bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SSH_HOME=~/.ssh
DEVEN_NAME=deven
DEVEN_NAMESPACE=deven
KUBE_CLUSTER=$(basename $(kubectl config view -o jsonpath='{.clusters[].cluster.server}') | cut -d':' -f1)

if [ ! -f $SSH_HOME/$DEVEN_NAME-id_rsa ]; then
    ssh-keygen -t rsa -b 4096 -f $SSH_HOME/$DEVEN_NAME-id_rsa -q -N ""
fi

terraform -chdir="$SCRIPT_DIR/.deven-k8s" apply \
    -var "current-user=$USER" \
    -var "public-key-file=$SSH_HOME/$DEVEN_NAME-id_rsa.pub" \
    -var "deven-instance-name=$DEVEN_NAME" \
    -var "deven-namespace=$DEVEN_NAMESPACE" \
    -var "workspace-git-repo=https://github.com/rennochj/deven.git"  \
    -var "deven-image=ghcr.io/rennochj/deven-amazon-base:latest"  \
    -var "kubernetes-cluster=$KUBE_CLUSTER" \
    -auto-approve $@ 

SSH_PORT=$(terraform -chdir="$SCRIPT_DIR/.deven-k8s" output -raw "ssh-port")
DEVEN_NAME=$(terraform -chdir="$SCRIPT_DIR/.deven-k8s" output -raw "deven-pod-name")
HOST=$(terraform -chdir="$SCRIPT_DIR/.deven-k8s" output -raw "kubernetes-cluster")

if [ ! -d $SSH_HOME/config.d ]; then

    echo "Creating ~/.ssh/config.d"
    mkdir -p $SSH_HOME/config.d

    if [ -f $SSH_HOME/config ]; then
        echo "Moving ~/.ssh/config"
        mv $SSH_HOME/config $SSH_HOME/config.d/
    fi

fi

touch $SSH_HOME/config.d/$DEVEN_NAME.config
printf "HOST $DEVEN_NAME\n    HostName $HOST\n    User deven\n    Port $SSH_PORT\n    IdentityFile $SSH_HOME/$DEVEN_NAME-id_rsa\n    StrictHostKeyChecking no\n    UserKnownHostsFile /dev/null\n\n" > ~/.ssh/config.d/$DEVEN_NAME.config

touch $SSH_HOME/config
printf "# This file is machine generated from the concatenation of all configuration files from config.d\n" > $SSH_HOME/config
printf "# cat config.d/* > ./config\n\n" >> $SSH_HOME/config
cat $SSH_HOME/config.d/* >> $SSH_HOME/config

