#! /bin/bash

# -- Initialize -------------------------------------------------------------------------------------------------------

set -e

DEVEN_DIRECTORY="./.deven"
DEVEN_DESTROY=""
DEVEN_MODULE_LOCATION=../../../modules

DEVEN_SSH_HOME=~/.ssh
DEVEN_SSH_PORT=2222
DEVEN_SSH_USER=deven
DEVEN_INSTANCE_NAME="deven"

# -- Process options --------------------------------------------------------------------------------------------------

usage() {
  echo "\
deven-compute [-h]                # help
              [-d]                # destroy 
              [-s]                # .ssh directory (default $DEVEN_SSH_HOME)
              [-p]                # ssh port (default - $DEVEN_SSH_PORT)
              [-n]                # deven instance name (default - $DEVEN_INSTANCE_NAME)
              [deven-directory]   # director of the deven configuration directory (default - $DEVEN_DIRECTORY)

All options must preceed the deven-directory argument.
"
}

while getopts "hds:p:n:" option
do

  case $option in

    h) usage ; exit ;;
    d) DEVEN_DESTROY="-destroy" ;;
    s) DEVEN_SSH_HOME=$OPTARG ;;
    p) DEVEN_SSH_PORT=$OPTARG ;;
    n) DEVEN_INSTANCE_NAME=$OPTARG ;;
    ?) usage ; exit ;;

  esac

done

shift $(expr $OPTIND - 1)

if [[ ! -z $@ ]]
then
  DEVEN_DIRECTORY=$1
fi

# -- Build Templates --------------------------------------------------------------------------------------------------

DEVEN_SSH_PRIVATE_KEY="deven-id_rsa"
DEVEN_SSH_PUBLIC_KEY="deven-id_rsa.pub"
FULL_DEVEN_DIRECTORY="$(pwd)/$DEVEN_DIRECTORY/compute/"

[[ -f "$DEVEN_DIRECTORY/setup.deven" ]] && source "$DEVEN_DIRECTORY/setup.deven"

for file in "$DEVEN_DIRECTORY/compute/*.deven"; do
    source $file
    terraform -chdir=$DEVEN_DIRECTORY/compute fmt
done

# -- Create SSH Keys --------------------------------------------------------------------------------------------------

if [ ! -f "$FULL_DEVEN_DIRECTORY/$DEVEN_SSH_PRIVATE_KEY" ]; then
    echo "Creating a new ssh private key - $FULL_DEVEN_DIRECTORY/$DEVEN_SSH_PRIVATE_KEY"
    ssh-keygen -t rsa -b 4096 -f "$FULL_DEVEN_DIRECTORY/$DEVEN_SSH_PRIVATE_KEY" -q -N ""
fi

# -- Execute ----------------------------------------------------------------------------------------------------------

if [[ -z $DEVEN_DESTROY ]]
then

  echo "DEVEN Environment Variables ---------------------------------------------"
  set | grep -E DEVEN_.*=
  echo "DEVEN Environment Variables ---------------------------------------------"

  terraform -chdir="$FULL_DEVEN_DIRECTORY" init -upgrade
  terraform -chdir="$FULL_DEVEN_DIRECTORY" apply -auto-approve $DEVEN_DESTROY

else

  terraform -chdir="$FULL_DEVEN_DIRECTORY" apply -auto-approve $DEVEN_DESTROY

  rm $FULL_DEVEN_DIRECTORY/$DEVEN_SSH_PRIVATE_KEY $FULL_DEVEN_DIRECTORY/$DEVEN_SSH_PRIVATE_KEY.pub

fi

# -- Connect ----------------------------------------------------------------------------------------------------------

if [[ -z "$DEVEN_DESTROY" ]];
then

  DEVEN_HOST=$(terraform -chdir="$FULL_DEVEN_DIRECTORY" output -raw "host")
  PROXY_COMMAND=$(terraform -chdir="$FULL_DEVEN_DIRECTORY" output -raw "proxy_command" 2> /dev/null || true)

  if [[ -z $PROXY_COMMAND ]]
  then
    HOST_OR_PROXY="HostName $DEVEN_HOST"
  else
    HOST_OR_PROXY="ProxyCommand sh -c '$PROXY_COMMAND'"
  fi

  if [ ! -d $DEVEN_SSH_HOME/config.d ]; then

      echo "Creating ~/.ssh/config.d"
      mkdir -p $DEVEN_SSH_HOME/config.d

      if [ -f $DEVEN_SSH_HOME/config ]; then
          echo "Moving ~/.ssh/config"
          mv $DEVEN_SSH_HOME/config $DEVEN_SSH_HOME/config.d/
      fi

  fi

  touch $DEVEN_SSH_HOME/config.d/$DEVEN_INSTANCE_NAME.config
  cat <<EOF > ~/.ssh/config.d/$DEVEN_INSTANCE_NAME.config

  HOST $DEVEN_INSTANCE_NAME
    $HOST_OR_PROXY
    User $DEVEN_SSH_USER
    Port $DEVEN_SSH_PORT
    IdentityFile $FULL_DEVEN_DIRECTORY/$DEVEN_SSH_PRIVATE_KEY
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    NoHostAuthenticationForLocalhost no
    LogLevel Error

EOF

  cat ~/.ssh/config.d/$DEVEN_INSTANCE_NAME.config

  touch $DEVEN_SSH_HOME/config
  printf "# This file is machine generated from the concatenation of all configuration files from config.d\n" > $DEVEN_SSH_HOME/config
  printf "# cat config.d/* > ./config\n\n" >> $DEVEN_SSH_HOME/config
  cat $DEVEN_SSH_HOME/config.d/* >> $DEVEN_SSH_HOME/config

  ssh-keygen -R "[$DEVEN_HOST]:$DEVEN_SSH_PORT" 2> /dev/null

  echo "Access to this server by 'ssh $DEVEN_INSTANCE_NAME'"

fi